var $RecipeLogic$Status = Java.loadClass("com.gregtechceu.gtceu.api.machine.trait.RecipeLogic$Status");

GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
    event
        .create("cosmos_simulation")
        .category("transcendent")
        .setEUIO("in")
        .setMaxIOSize(1, 56, 0, 16)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.SCIENCE);
});

GTCEuStartupEvents.registry("gtceu:machine", event => {
    event
        .create("eye_of_harmony", "multiblock")
        .rotationState(RotationState.ALL)
        .recipeTypes([GTRecipeTypes.get("cosmos_simulation")])
        .appearanceBlock(() => Block.getBlock("gtceu:high_power_casing"))
        .pattern(definition =>
            FactoryBlockPattern.start()
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "            AAAAAAAAA           ",
                    "               A A              ",
                    "            AAAAAAAAA           ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "              BBBBB             ",
                    "             BBABABB            ",
                    "         AAAABAABAABAAAA        ",
                    "             BBBBBBB            ",
                    "         AAAABAABAABAAAA        ",
                    "             BBABABB            ",
                    "              BBBBB             ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "                B               ",
                    "             BBBBBBB            ",
                    "            BB     BB           ",
                    "            B  CCC  B           ",
                    "       AAA  B CDDDC B  AAA      ",
                    "          BBB CDDDC BBB         ",
                    "       AAA  B CDDDC B  AAA      ",
                    "            B  CCC  B           ",
                    "            BB     BB           ",
                    "             BBBBBBB            ",
                    "                B               ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "                B               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "      AA                 AA     ",
                    "        BB             BB       ",
                    "      AA                 AA     ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                B               ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "              AAAAA             ",
                    "                B               ",
                    "                D               ",
                    "                D               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "      A                   A     ",
                    "     AA                   AA    ",
                    "      ABDD             DDBA     ",
                    "     AA                   AA    ",
                    "      A                   A     ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                D               ",
                    "                D               ",
                    "                B               ",
                    "              AAAAA             ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "             ECCDCCE            ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "       E                 E      ",
                    "       C                 C      ",
                    "    AA C                 C AA   ",
                    "      BD                 DB     ",
                    "    AA C                 C AA   ",
                    "       C                 C      ",
                    "       E                 E      ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "             ECCDCCE            ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "              AAAAA             ",
                    "                B               ",
                    "                D               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "    A                       A   ",
                    "   AA                       AA  ",
                    "    ABD                   DBA   ",
                    "   AA                       AA  ",
                    "    A                       A   ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                D               ",
                    "                B               ",
                    "              AAAAA             ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "             ECCDCCE            ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "     E                     E    ",
                    "     C                     C    ",
                    "  AA C                     C AA ",
                    "    BD                     DB   ",
                    "  AA C                     C AA ",
                    "     C                     C    ",
                    "     E                     E    ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "             ECCDCCE            ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "               A A              ",
                    "                B               ",
                    "                D               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "  A                           A ",
                    "   BD                       DB  ",
                    "  A                           A ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                D               ",
                    "                B               ",
                    "               A A              ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "                D               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    " AA                           AA",
                    "   BD                       DB  ",
                    " AA                           AA",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                D               ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "                                "
                )
                .aisle(
                    "               A A              ",
                    "                B               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    " A                             A",
                    "  B                           B ",
                    " A                             A",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                B               ",
                    "               A A              ",
                    "                                "
                )
                .aisle(
                    "               A A              ",
                    "                B               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    " A                             A",
                    "  B                           B ",
                    " A                             A",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                B               ",
                    "               A A              ",
                    "                                "
                )
                .aisle(
                    "               A A              ",
                    "             BBBBBBB            ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "  B                           B ",
                    "  B                           B ",
                    "AAB                           BA",
                    "  B                           B ",
                    "AAB                           BA",
                    "  B                           B ",
                    "  B                           B ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "             BBBBBBB            ",
                    "               A A              ",
                    "               A A              "
                )
                .aisle(
                    "              BBBBB             ",
                    "            BB     BB           ",
                    "                                ",
                    "                                ",
                    "       E                 E      ",
                    "                                ",
                    "     E                     E    ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "  B                           B ",
                    "  B                           B ",
                    " B                             B",
                    "AB                             B",
                    " B                             B",
                    "AB                             B",
                    " B                             B",
                    "  B                           B ",
                    "  B                           B ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "     E                     E    ",
                    "                                ",
                    "       E                 E      ",
                    "                                ",
                    "                                ",
                    "            BB     BB           ",
                    "              BBBBB             ",
                    "               A A              "
                )
                .aisle(
                    "             BBABABB            ",
                    "            B  CCC  B           ",
                    "                                ",
                    "      A                   A     ",
                    "       C                 C      ",
                    "    A                       A   ",
                    "     C                     C    ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "  B                           B ",
                    " B                             B",
                    " B                             B",
                    "AAC                           CA",
                    " BC                           CB",
                    "AAC                           CA",
                    " B                             B",
                    " B                             B",
                    "  B                           B ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "     C                     C    ",
                    "    A                       A   ",
                    "       C                 C      ",
                    "      A                   A     ",
                    "                                ",
                    "            B  CCC  B           ",
                    "             BBABABB            ",
                    "               A A              "
                )
                .aisle(
                    "         AAAABAABAABAAAA        ",
                    "       AAA  B CDDDC B  AAA      ",
                    "      AA                 AA     ",
                    "     AA                   AA    ",
                    "    AA C                 C AA   ",
                    "   AA                       AA  ",
                    "  AA C                     C AA ",
                    "  A                           A ",
                    " AA                           AA",
                    " A                             A",
                    " A                             A",
                    "AAB                           BA",
                    "AB                             B",
                    "AAC                           CA",
                    "AAD                           DA",
                    "ABD                           DB",
                    "AAD                           DA",
                    "AAC                           CA",
                    "AB                             B",
                    "AAB                           BA",
                    " A                             A",
                    " A                             A",
                    " AA                           AA",
                    "  A                           A ",
                    "  AA C                     C AA ",
                    "   AA                       AA  ",
                    "    AA C                 C AA   ",
                    "     AA                   AA    ",
                    "      AA                 AA     ",
                    "       AAA  B CDDDC B  AAA      ",
                    "         AAAABAABAABAAAA        ",
                    "            AAAAAAAAA           "
                )
                .aisle(
                    "             BBBBBBB            ",
                    "          BBB CDDDC BBB         ",
                    "        BB             BB       ",
                    "      ABDD             DDBA     ",
                    "      BD                 DB     ",
                    "    ABD                   DBA   ",
                    "    BD                     DB   ",
                    "   BD                       DB  ",
                    "   BD                       DB  ",
                    "  B                           B ",
                    "  B                           B ",
                    "  B                           B ",
                    " B                             B",
                    " BC                           CB",
                    "ABD                           DB",
                    " BD                           DB",
                    "ABD                           DB",
                    " BC                           CB",
                    " B                             B",
                    "  B                           B ",
                    "  B                           B ",
                    "  B                           B ",
                    "   BD                       DB  ",
                    "   BD                       DB  ",
                    "    BD                     DB   ",
                    "    ABD                   DBA   ",
                    "      BD                 DB     ",
                    "      ABDD             DDBA     ",
                    "        BB             BB       ",
                    "          BBB CDDDC BBB         ",
                    "             BBBBBBB            ",
                    "               A A              "
                )
                .aisle(
                    "         AAAABAABAABAAAA        ",
                    "       AAA  B CDDDC B  AAA      ",
                    "      AA                 AA     ",
                    "     AA                   AA    ",
                    "    AA C                 C AA   ",
                    "   AA                       AA  ",
                    "  AA C                     C AA ",
                    "  A                           A ",
                    " AA                           AA",
                    " A                             A",
                    " A                             A",
                    "AAB                           BA",
                    "AB                             B",
                    "AAC                           CA",
                    "AAD                           DA",
                    "ABD                           DB",
                    "AAD                           DA",
                    "AAC                           CA",
                    "AB                             B",
                    "AAB                           BA",
                    " A                             A",
                    " A                             A",
                    " AA                           AA",
                    "  A                           A ",
                    "  AA C                     C AA ",
                    "   AA                       AA  ",
                    "    AA C                 C AA   ",
                    "     AA                   AA    ",
                    "      AA                 AA     ",
                    "       AAA  B CDDDC B  AAA      ",
                    "         AAAABAABAABAAAA        ",
                    "            AAAAAAAAA           "
                )
                .aisle(
                    "             BBABABB            ",
                    "            B  CCC  B           ",
                    "                                ",
                    "      A                   A     ",
                    "       C                 C      ",
                    "    A                       A   ",
                    "     C                     C    ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "  B                           B ",
                    " B                             B",
                    " B                             B",
                    "AAC                           CA",
                    " BC                           CB",
                    "AAC                           CA",
                    " B                             B",
                    " B                             B",
                    "  B                           B ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "     C                     C    ",
                    "    A                       A   ",
                    "       C                 C      ",
                    "      A                   A     ",
                    "                                ",
                    "            B  CCC  B           ",
                    "             BBABABB            ",
                    "               A A              "
                )
                .aisle(
                    "              BBBBB             ",
                    "            BB     BB           ",
                    "                                ",
                    "                                ",
                    "       E                 E      ",
                    "                                ",
                    "     E                     E    ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "  B                           B ",
                    "  B                           B ",
                    " B                             B",
                    "AB                             B",
                    " B                             B",
                    "AB                             B",
                    " B                             B",
                    "  B                           B ",
                    "  B                           B ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "     E                     E    ",
                    "                                ",
                    "       E                 E      ",
                    "                                ",
                    "                                ",
                    "            BB     BB           ",
                    "              BBBBB             ",
                    "               A A              "
                )
                .aisle(
                    "               A A              ",
                    "             BBBBBBB            ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "  B                           B ",
                    "  B                           B ",
                    "AAB                           BA",
                    "  B                           B ",
                    "AAB                           BA",
                    "  B                           B ",
                    "  B                           B ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "             BBBBBBB            ",
                    "               A A              ",
                    "               A A              "
                )
                .aisle(
                    "               A A              ",
                    "                B               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    " A                             A",
                    "  B                           B ",
                    " A                             A",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                B               ",
                    "               A A              ",
                    "                                "
                )
                .aisle(
                    "               A A              ",
                    "                B               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    " A                             A",
                    "  B                           B ",
                    " A                             A",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                B               ",
                    "               A A              ",
                    "                                "
                )
                .aisle(
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "                D               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    " AA                           AA",
                    "   BD                       DB  ",
                    " AA                           AA",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                D               ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "               A A              ",
                    "                B               ",
                    "                D               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "  A                           A ",
                    "   BD                       DB  ",
                    "  A                           A ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                D               ",
                    "                B               ",
                    "               A A              ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "             ECCDCCE            ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "     E                     E    ",
                    "     C                     C    ",
                    "  AA C                     C AA ",
                    "    BD                     DB   ",
                    "  AA C                     C AA ",
                    "     C                     C    ",
                    "     E                     E    ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "             ECCDCCE            ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "              AAAAA             ",
                    "                B               ",
                    "                D               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "    A                       A   ",
                    "   AA                       AA  ",
                    "    ABD                   DBA   ",
                    "   AA                       AA  ",
                    "    A                       A   ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                D               ",
                    "                B               ",
                    "              AAAAA             ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "             ECCDCCE            ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "       E                 E      ",
                    "       C                 C      ",
                    "    AA C                 C AA   ",
                    "      BD                 DB     ",
                    "    AA C                 C AA   ",
                    "       C                 C      ",
                    "       E                 E      ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "             ECCDCCE            ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "              AAAAA             ",
                    "                B               ",
                    "                D               ",
                    "                D               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "      A                   A     ",
                    "     AA                   AA    ",
                    "      ABDD             DDBA     ",
                    "     AA                   AA    ",
                    "      A                   A     ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                D               ",
                    "                D               ",
                    "                B               ",
                    "              AAAAA             ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "                B               ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "      AA                 AA     ",
                    "        BB             BB       ",
                    "      AA                 AA     ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                B               ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "                B               ",
                    "                B               ",
                    "             BBBBBBB            ",
                    "            BB     BB           ",
                    "            B  CCC  B           ",
                    "       AAA  B CDDDC B  AAA      ",
                    "          BBB CDDDC BBB         ",
                    "       AAA  B CDDDC B  AAA      ",
                    "            B  CCC  B           ",
                    "            BB     BB           ",
                    "             BBBBBBB            ",
                    "                B               ",
                    "                B               ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "              BBBBB             ",
                    "             BBABABB            ",
                    "         AAAABAABAABAAAA        ",
                    "             BBBBBBB            ",
                    "         AAAABAABAABAAAA        ",
                    "             BBABABB            ",
                    "              BBBBB             ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "               A A              ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .aisle(
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "             AAAAAAA            ",
                    "            AAFFFFFAA           ",
                    "            AFFFFFFFA           ",
                    "            AFFAAAFFA           ",
                    "            AFFA@AFFA           ",
                    "            AFFAAAFFA           ",
                    "            AFFFFFFFA           ",
                    "            AAFFFFFAA           ",
                    "             AAAAAAA            ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                ",
                    "                                "
                )
                .where("A", Predicates.blocks("kubejs:dimension_connection_casing"))
                .where("B", Predicates.blocks("gtceu:high_power_casing"))
                .where("C", Predicates.blocks("kubejs:dimension_creation_casing"))
                .where("D", Predicates.blocks("kubejs:containment_field_generator"))
                .where("E", Predicates.blocks("kubejs:dimensional_stability_casing"))
                .where("F", Predicates.blocks("gtceu:high_power_casing"))
                .where(" ", Predicates.blocks("minecraft:air"))
                .where("@", Predicates.controller(Predicates.blocks(definition.get())))
                .build()
        )
        .modelProperty(GTModelProperties.RECIPE_LOGIC_STATUS, $RecipeLogic$Status.IDLE)
        .model(
            GTMachineModels.createWorkableCasingMachineModel(
                "gtceu:block/casings/hpca/high_power_casing",
                "gtceu:block/multiblock/power_substation"
            )["andThen(java.util.function.Consumer)"](b =>
                b.addDynamicRenderer(() => KubeJSDynamicRender.of("kubejs:eye_of_harmony"))
            )
        );
});

GTRenderJSEvents.registerModelsForRender(event => {
    event.register("kubejs:obj/space");
    event.register("kubejs:obj/star");
    event.register("kubejs:obj/the_nether");
    event.register("kubejs:obj/overworld");
    event.register("kubejs:obj/the_end");
});
