var $RecipeLogic$Status = Java.loadClass("com.gregtechceu.gtceu.api.machine.trait.RecipeLogic$Status");

GTCEuStartupEvents.registry("gtceu:recipe_type", event => {
    event
        .create("cosmos_simulation")
        .category("transcendent")
        .setEUIO("in")
        .setMaxIOSize(1, 56, 0, 16)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.SCIENCE);
});

GTCEuStartupEvents.registry("gtceu:machine", event => {
    event
        .create("heart_of_universe", "multiblock")
        .rotationState(RotationState.ALL)
        .recipeTypes([GTRecipeTypes.get("cosmos_simulation")])
        .appearanceBlock(() => Block.getBlock("kubejs:dimension_connection_casing"))
        .pattern(definition =>
            FactoryBlockPattern.start()
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           AAA           ",
                    "          AAAAA          ",
                    "         AAAAAAA         ",
                    "          AAAAA          ",
                    "           AAA           ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "            A            ",
                    "           ACA           ",
                    "           DCD           ",
                    "         AAACAAA         ",
                    "       AACCBCBCCAA       ",
                    "         AAACAAA         ",
                    "           DCD           ",
                    "           ACA           ",
                    "            A            ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "            A            ",
                    "           ACA           ",
                    "           ACA           ",
                    "          D   D          ",
                    "         DABBBAD         ",
                    "       AA B   B AA       ",
                    "     AACC B   B CCAA     ",
                    "       AA B   B AA       ",
                    "         DABBBAD         ",
                    "          D   D          ",
                    "           ACA           ",
                    "           ACA           ",
                    "            A            ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "           ACA           ",
                    "          A   A          ",
                    "          A   A          ",
                    "                         ",
                    "       AA       AA       ",
                    "     AA           AA     ",
                    "    ACC           CCA    ",
                    "     AA           AA     ",
                    "       AA       AA       ",
                    "                         ",
                    "          A   A          ",
                    "          A   A          ",
                    "           ACA           ",
                    "           ACA           ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "           D D           ",
                    "          A   A          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "      A           A      ",
                    "    AD             DA    ",
                    "   AC               CA   ",
                    "    AD             DA    ",
                    "      A           A      ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          A   A          ",
                    "           D D           ",
                    "           ACA           ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "           D D           ",
                    "          A   A          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "     A             A     ",
                    "   AD               DA   ",
                    "  AC                 CA  ",
                    "   AD               DA   ",
                    "     A             A     ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          A   A          ",
                    "           D D           ",
                    "           ACA           ",
                    "            A            ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "          A   A          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "    A               A    ",
                    "   A                 A   ",
                    "  AC                 CA  ",
                    "   A                 A   ",
                    "    A               A    ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          A   A          ",
                    "           ACA           ",
                    "            A            ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "          AC CA          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "   A                 A   ",
                    "  A                   A  ",
                    " AC                   CA ",
                    "  A                   A  ",
                    "   A                 A   ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          AC CA          ",
                    "           ACA           ",
                    "            A            ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "          AB BA          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "   A                 A   ",
                    "  A                   A  ",
                    " AC                   CA ",
                    "  A                   A  ",
                    "   A                 A   ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          AB BA          ",
                    "           ACA           ",
                    "            A            ",
                    "                         "
                )
                .aisle(
                    "            A            ",
                    "           ABA           ",
                    "          AC CA          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "  D                   D  ",
                    " A                     A ",
                    "AC                     CA",
                    " A                     A ",
                    "  D                   D  ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          AC CA          ",
                    "           ABA           ",
                    "            A            "
                )
                .aisle(
                    "           AAA           ",
                    "           ABA           ",
                    "         ADABADA         ",
                    "       AA       AA       ",
                    "      A           A      ",
                    "     A             A     ",
                    "    A               A    ",
                    "   A                 A   ",
                    "   A                 A   ",
                    "  D                   D  ",
                    "  A                   A  ",
                    "AAB                   BAA",
                    "ACB                   BCA",
                    "AAB                   BAA",
                    "  A                   A  ",
                    "  D                   D  ",
                    "   A                 A   ",
                    "   A                 A   ",
                    "    A               A    ",
                    "     A             A     ",
                    "      A           A      ",
                    "       AA       AA       ",
                    "         ADABADA         ",
                    "           ABA           ",
                    "           AAA           "
                )
                .aisle(
                    "          AAAAA          ",
                    "         AABBBAA         ",
                    "       AACA   ACAA       ",
                    "     AACB       BCAA     ",
                    "    AD             DA    ",
                    "   AD               DA   ",
                    "   A                 A   ",
                    "  A                   A  ",
                    "  A                   A  ",
                    " A                     A ",
                    "ADB                   BDA",
                    "AA                     AA",
                    "AB                     BA",
                    "AA                     AA",
                    "ADB                   BDA",
                    " A                     A ",
                    "  A                   A  ",
                    "  A                   A  ",
                    "   A                 A   ",
                    "   AD               DA   ",
                    "    AD             DA    ",
                    "     AACB       BCAA     ",
                    "       AACA   ACAA       ",
                    "         AABBBAA         ",
                    "          AAAAA          "
                )
                .aisle(
                    "         AAAAAAA         ",
                    "       AABBBBBBBAA       ",
                    "     AACC B   B CCAA     ",
                    "    ACC           CCA    ",
                    "   AC               CA   ",
                    "  AC                 CA  ",
                    "  AC                 CA  ",
                    " AC                   CA ",
                    " AC                   CA ",
                    "AC                     CA",
                    "ACB                   BCA",
                    "AC                     CA",
                    "AC                     CA",
                    "AC                     CA",
                    "ACB                   BCA",
                    "AC                     CA",
                    " AC                   CA ",
                    " AC                   CA ",
                    "  AC                 CA  ",
                    "  AC                 CA  ",
                    "   AC               CA   ",
                    "    ACC           CCA    ",
                    "     AACC B   B CCAA     ",
                    "       AABBBBBBBAA       ",
                    "         AAAAAAA         "
                )
                .aisle(
                    "          AAAAA          ",
                    "         AABBBAA         ",
                    "       AACA   ACAA       ",
                    "     AACB       BCAA     ",
                    "    AD             DA    ",
                    "   AD               DA   ",
                    "   A                 A   ",
                    "  A                   A  ",
                    "  A                   A  ",
                    " A                     A ",
                    "ADB                   BDA",
                    "AA                     AA",
                    "AB                     BA",
                    "AA                     AA",
                    "ADB                   BDA",
                    " A                     A ",
                    "  A                   A  ",
                    "  A                   A  ",
                    "   A                 A   ",
                    "   AD               DA   ",
                    "    AD             DA    ",
                    "     AACB       BCAA     ",
                    "       AACA   ACAA       ",
                    "         AABBBAA         ",
                    "          AAAAA          "
                )
                .aisle(
                    "           AAA           ",
                    "           ABA           ",
                    "         ADABADA         ",
                    "       AA       AA       ",
                    "      A           A      ",
                    "     A             A     ",
                    "    A               A    ",
                    "   A                 A   ",
                    "   A                 A   ",
                    "  D                   D  ",
                    "  A                   A  ",
                    "AAB                   BAA",
                    "ACB                   BCA",
                    "AAB                   BAA",
                    "  A                   A  ",
                    "  D                   D  ",
                    "   A                 A   ",
                    "   A                 A   ",
                    "    A               A    ",
                    "     A             A     ",
                    "      A           A      ",
                    "       AA       AA       ",
                    "         ADABADA         ",
                    "           ABA           ",
                    "           AAA           "
                )
                .aisle(
                    "            A            ",
                    "           ABA           ",
                    "          AC CA          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "  D                   D  ",
                    " A                     A ",
                    "AC                     CA",
                    " A                     A ",
                    "  D                   D  ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          AC CA          ",
                    "           ABA           ",
                    "            A            "
                )
                .aisle(
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "          AB BA          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "   A                 A   ",
                    "  A                   A  ",
                    " AC                   CA ",
                    "  A                   A  ",
                    "   A                 A   ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          AB BA          ",
                    "           ACA           ",
                    "            A            ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "          AC CA          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "   A                 A   ",
                    "  A                   A  ",
                    " AC                   CA ",
                    "  A                   A  ",
                    "   A                 A   ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          AC CA          ",
                    "           ACA           ",
                    "            A            ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "          A   A          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "    A               A    ",
                    "   A                 A   ",
                    "  AC                 CA  ",
                    "   A                 A   ",
                    "    A               A    ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          A   A          ",
                    "           ACA           ",
                    "            A            ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "           D D           ",
                    "          A   A          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "     A             A     ",
                    "   AD               DA   ",
                    "  AC                 CA  ",
                    "   AD               DA   ",
                    "     A             A     ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          A   A          ",
                    "           D D           ",
                    "           ACA           ",
                    "            A            ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "           D D           ",
                    "          A   A          ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "      A           A      ",
                    "    AD             DA    ",
                    "   AC               CA   ",
                    "    AD             DA    ",
                    "      A           A      ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "          A   A          ",
                    "           D D           ",
                    "           ACA           ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           ACA           ",
                    "           ACA           ",
                    "          A   A          ",
                    "          A   A          ",
                    "                         ",
                    "       AA       AA       ",
                    "     AA           AA     ",
                    "    ACC           CCA    ",
                    "     AA           AA     ",
                    "       AA       AA       ",
                    "                         ",
                    "          A   A          ",
                    "          A   A          ",
                    "           ACA           ",
                    "           ACA           ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "            A            ",
                    "           ACA           ",
                    "           ACA           ",
                    "          D   D          ",
                    "         DABBBAD         ",
                    "       AA B   B AA       ",
                    "     AACC B   B CCAA     ",
                    "       AA B   B AA       ",
                    "         DABBBAD         ",
                    "          D   D          ",
                    "           ACA           ",
                    "           ACA           ",
                    "            A            ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "            A            ",
                    "           ACA           ",
                    "           DCD           ",
                    "         AAACAAA         ",
                    "       AACCBCBCCAA       ",
                    "         AAACAAA         ",
                    "           DCD           ",
                    "           ACA           ",
                    "            A            ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .aisle(
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "            A            ",
                    "           AAA           ",
                    "          AAAAA          ",
                    "         AAAEAAA         ",
                    "          AAAAA          ",
                    "           AAA           ",
                    "            A            ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         ",
                    "                         "
                )
                .where("E", Predicates.controller(Predicates.blocks(definition.get())))
                .where(
                    "D",
                    Predicates.blocks("kubejs:dimensional_stability_casing") // ← 修正
                        .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1))
                        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(5))
                        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS_4X).setMaxGlobalLimited(5))
                        .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS_9X).setMaxGlobalLimited(5))
                        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                        .or(Predicates.abilities(PartAbility.INPUT_LASER).setMaxGlobalLimited(10))
                )
                .where("A", Predicates.blocks("kubejs:dimension_connection_casing"))
                .where("B", Predicates.blocks("kubejs:dimension_creation_casing"))
                .where("C", Predicates.blocks("kubejs:containment_field_generator"))
                .where("_", Predicates.any()) // 空白許容
                .build()
        )

        .modelProperty(GTModelProperties.RECIPE_LOGIC_STATUS, $RecipeLogic$Status.IDLE)
        .model(
            GTMachineModels.createWorkableCasingMachineModel(
                "kubejs:block/casings/eoh/dimension_connection_casing",
                "gtceu:block/multiblock/power_substation"
            )["andThen(java.util.function.Consumer)"](b =>
                b.addDynamicRenderer(() => KubeJSDynamicRender.of("kubejs:eye_of_harmony"))
            )
        );
});

GTRenderJSEvents.registerModelsForRender(event => {
    event.register("kubejs:obj/space");
    event.register("kubejs:obj/star");
    event.register("kubejs:obj/the_nether");
    event.register("kubejs:obj/overworld");
    event.register("kubejs:obj/the_end");
});
